name: opencv-cuda102-hello
base: core20
version: '0.2'
summary: Example snap package to run OpenCV on CUDA 10.2
description: |
  Example snap package to run OpenCV on CUDA 10.2
grade: stable
confinement: strict

architectures:
  - build-on: arm64
    run-on: arm64

apps:
  opencv-cuda102-hello:
    command: bin/main.py
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/var/lib/snapd/hostfs/usr/lib:$SNAP/lib:$SNAP/lib/aarch64-linux-gnu:$SNAP/usr/lib/aarch64-linux-gnu:$SNAP/usr/lib/aarch64-linux-gnu/openblas-pthread
      PYTHONPATH: $SNAP/lib/python3.8/site-packages
    plugs:
      - network
      - network-bind
      - opengl

parts:
  autobahn:
    plugin: nil
    source: .
    override-build: |
      snapcraftctl build
      pip3 install --ignore-installed --prefix $SNAPCRAFT_PART_INSTALL autobahn[serialization,twisted] numpy Pillow
      pip3 install --prefix $SNAPCRAFT_PART_INSTALL ./torch-1.7.0-cp38-cp38-linux_aarch64.whl torchvision
      find $SNAPCRAFT_PART_INSTALL -name '*.so*' -exec strip {} \;
    stage-packages:
      - libsnappy1v5
      - libgfortran5
      - libopenblas0
      # Actually required by opencv part, however installing libgomp1 pulls in
      # libpthread, which then conflcits with the one pulled by libopenblas0
      - libgomp1
    build-packages:
      - build-essential
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - python3-pip
      - python3-dev
      - libsnappy-dev
  data:
    plugin: dump
    source: .
    organize:
      main.py: bin/main.py
    prime:
      - haarcascade_frontalface_default.xml
      - bin/main.py
  opencv:
    source: http://download.crossbario.com/crossbarfx-os/opencv-4.5.0-aarch64.tar.gz
    source-type: tar
    plugin: dump
